apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/backend
images:
  - name: webserver-backend
    newName: webserveracr.azurecr.io/mic-orders:07480ec2
    newTag: 07480ec2
