apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/backend
images:
- name: webserveracr.azurecr.io/mic-orders
  newName: webserveracr.azurecr.io/mic-orders
  newTag: 2c7f4c07
