apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-backend
spec:
  template:
    spec:
      containers:
        - name: webserver-backend
          image: webserveracr.azurecr.io/mic-orders:9b0a74dd
