apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-backend
  namespace: webserver
spec:
  template:
    spec:
      containers:
        - name: webserver-backend
          image: webserveracr.azurecr.io/mic-orders:3bb2d935
