apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  namespace: webserver
  annotations: 
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: azure-keyvault-secret-store
    kind: SecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-username
      remoteRef:
        key: postgres-username
    - secretKey: postgres-password
      remoteRef:
        key: postgres-password
