apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-pv.yaml
  - postgres-pvc.yaml
  - postgres-ss.yaml
  - postgres-service.yaml
  - serviceaccount.yaml
  - secretstore.yaml
  - externalsecret.yaml
