apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: azure-keyvault-secret-store
spec:
  provider:
    azurekv:
      tenantId: 0f970ba5-6ade-4622-9b48-5493680fc107
      authType: ManagedIdentity
      vaultUrl: https://webserver.vault.azure.net/