apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: azure-keyvault-secret-store
spec:
  provider:
    azurekv:
      clientId: c679abaf-e6e4-46d5-8ce9-88d0efbb68a6
      authType: ManagedIdentity
      vaultUrl: https://webserver.vault.azure.net/
