apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: azure-keyvault-secret-store
  namespace: webserver
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      tenantId: 0f970ba5-6ade-4622-9b48-5493680fc107
      vaultUrl: "https://webserver.vault.azure.net"
      serviceAccountRef:
        name: workload-identity-sa
