apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: azure-keyvault-secret-store
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      vaultUrl: https://webserver.vault.azure.net/