apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-backend
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-backend
  template:
    metadata:
      labels:
        app: webserver-backend
    spec:
      containers:
        - name: webserver-backend
          image: webserveracr.azurecr.io/mic-orders
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: DB_NAME
              value: retail
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: postgres:5432
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-username
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
