apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/frontend
images:
- name: webserveracr.azurecr.io/spa-orders
  newName: webserveracr.azurecr.io/spa-orders
  newTag: 63cf2cc3
