apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/frontend
images:
- name: webserveracr.azurecr.io/spa-orders
  newName: webserveracr.azurecr.io/spa-orders
  newTag: b7ae4a55
