apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocked-services
  namespace: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocked-services
  template:
    metadata:
      labels:
        app: mocked-services
    spec:
      containers:
        - name: mocked-services
          image: webserveracr.azurecr.io/mocked-services
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
