apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/mocked-services
images:
  - name: webserveracr.azurecr.io/mocked-services
    newName: webserveracr.azurecr.io/mocked-services
    newTag: a72f9095
